version: '3.8'

services:
  backend:
    build:
      context: ./idealo_scraper
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./idealo_data:/app/data
      - ./produkte.csv:/app/produkte.csv

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scraper.rule=Host(`hr.graef-ai-consulting.de`)"
      - "traefik.http.routers.scraper.tls=true"
      - "traefik.http.routers.scraper.entrypoints=websecure"
      - "traefik.http.routers.scraper.tls.certresolver=mytlschallenge"
      - "traefik.http.services.scraper.loadbalancer.server.port=80"
    networks:
      - default
      - traefik_public

networks:
  traefik_public:
    external: true
    name: root_default
